name: James Matson
favicon: null
layout_spectrum: 0.49034
typography_spectrum: 0.77113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e0d00'
    - '#6f4128'
    - '#ae8750'
    - '#b8b991'
    - '#eaecd4'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
