name: James Matson
favicon: null
layout_spectrum: 0.35851
typography_spectrum: 0.77113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffecb1'
    - '#a86d73'
    - '#f9947a'
    - '#731f1e'
    - '#e17e39'
  brandStrength: 0.8639051765203476
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
